# Generated by Django 2.1.8 on 2019-04-22 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='RdBox',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='rd_django_rdbox', serialize=False, to='cms.CMSPlugin')),
                ('boxtitle', models.CharField(max_length=40, verbose_name='Title of the box')),
                ('boxtitlecolor', models.CharField(default='black', max_length=40, verbose_name='Box title color')),
                ('boxbackgroundcolor', models.CharField(default='grey', max_length=40, verbose_name='Box background color title')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='RdGridCell',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='rd_django_rdgridcell', serialize=False, to='cms.CMSPlugin')),
                ('xs_size', models.CharField(blank=True, choices=[('', ''), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='', max_length=2, verbose_name='width cell for extra small display')),
                ('sm_size', models.CharField(blank=True, choices=[('', ''), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='', max_length=2, verbose_name='width cell for small display')),
                ('md_size', models.CharField(blank=True, choices=[('', ''), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='', max_length=2, verbose_name='width cell medium display')),
                ('lg_size', models.CharField(blank=True, choices=[('', ''), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='', max_length=2, verbose_name='width cell large display')),
                ('xl_size', models.CharField(blank=True, choices=[('', ''), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='', max_length=2, verbose_name='width cell extra large display')),
                ('xs_offset', models.CharField(blank=True, choices=[('', ''), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='', max_length=2, verbose_name='offset for extra small display')),
                ('sm_offset', models.CharField(blank=True, choices=[('', ''), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='', max_length=2, verbose_name='offset for small display')),
                ('md_offset', models.CharField(blank=True, choices=[('', ''), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='', max_length=2, verbose_name='offset medium display')),
                ('lg_offset', models.CharField(blank=True, choices=[('', ''), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='', max_length=2, verbose_name='offset large display')),
                ('xl_offset', models.CharField(blank=True, choices=[('', ''), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='', max_length=2, verbose_name='offset extra large display')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='RdGridContainer',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='rd_django_rdgridcontainer', serialize=False, to='cms.CMSPlugin')),
                ('container', models.CharField(blank=True, choices=[('fixed', 'Fixed container'), ('fluid', 'Fluid container')], default='fixed', max_length=20, verbose_name='Container type')),
                ('gutter', models.CharField(blank=True, choices=[('', 'no gutter'), ('xs', 'extra small gutter'), ('sm', 'small gutter'), ('md', 'medium gutter'), ('lg', 'large gutter'), ('xl', 'extra large gutter')], default='', max_length=3, verbose_name='Gutter between cells')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='RdGridLayout',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='rd_django_rdgridlayout', serialize=False, to='cms.CMSPlugin')),
                ('layout', models.CharField(choices=[('horizontal', 'Horizontal layout'), ('vertical', 'Vertical layout')], default='horizontal', max_length=20, verbose_name='direction')),
                ('wrap', models.BooleanField(default=True, verbose_name='Wrap cells if width is exceeded')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='RdIcon',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='rd_django_rdicon', serialize=False, to='cms.CMSPlugin')),
                ('icon', models.CharField(max_length=40, verbose_name='Icon')),
                ('size', models.CharField(blank=True, choices=[('', 'standard'), ('small', 'small'), ('medium', 'medium'), ('large', 'large'), ('x-large', 'extra large')], default='', max_length=10, verbose_name='size of icon')),
                ('color', models.CharField(blank=True, default='', max_length=30, verbose_name='Color')),
                ('theme', models.CharField(blank=True, choices=[('', 'standard'), ('dark', 'dark'), ('light', 'light')], default='', max_length=10, verbose_name='Theme')),
                ('additional_classes', models.CharField(blank=True, default='', max_length=255, verbose_name='Additional CSS classes (separated by a space)')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='RdTab',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='rd_django_rdtab', serialize=False, to='cms.CMSPlugin')),
                ('tabtitle', models.CharField(max_length=40, verbose_name='Title of the tab')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='RdTabGroup',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='rd_django_rdtabgroup', serialize=False, to='cms.CMSPlugin')),
                ('slidercolor', models.CharField(default='accent', max_length=40, verbose_name='Slider color')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
