# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-13 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        ('rd_django', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RdPerson',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='rd_django_rdperson', serialize=False, to='cms.CMSPlugin')),
                ('idbel', models.CharField(max_length=10, verbose_name='ID number RBCF')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='RdPersonGroup',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='rd_django_rdpersongroup', serialize=False, to='cms.CMSPlugin')),
                ('group', models.CharField(max_length=39, verbose_name='Group')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
