# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-21 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rd_django', '0002_auto_20180521_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdicon',
            name='theme',
            field=models.CharField(blank=True, choices=[('', 'standard'), ('dark', 'dark'), ('light', 'light')], default='', max_length=10, verbose_name='Them'),
        ),
        migrations.AlterField(
            model_name='rdicon',
            name='color',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Color'),
        ),
    ]
