# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-14 05:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        ('rd_django', '0002_rdperson_rdpersongroup_rdtab_rdtabgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='RdTab',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='rd_django_rdtab', serialize=False, to='cms.CMSPlugin')),
                ('tabtitle', models.CharField(max_length=40, verbose_name='Title of the tab')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='RdTabGroup',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='rd_django_rdtabgroup', serialize=False, to='cms.CMSPlugin')),
                ('slidercolor', models.CharField(default='accent', max_length=40, verbose_name='Slider color')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
