# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-10 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        ('rd_django', '0003_rdtab_rdtabgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='RdBox',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='rd_django_rdbox', serialize=False, to='cms.CMSPlugin')),
                ('boxtitle', models.CharField(max_length=40, verbose_name='Title of the box')),
                ('boxtitlecolor', models.CharField(default='accent', max_length=40, verbose_name='Box title color')),
                ('boxbackgroundcolor', models.CharField(default='black', max_length=40, verbose_name='Box backgroundcolor')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
