# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-15 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rd_django', '0004_rdbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdbox',
            name='boxbackgroundcolor',
            field=models.CharField(default='grey', max_length=40, verbose_name='Box background color title'),
        ),
        migrations.AlterField(
            model_name='rdbox',
            name='boxtitlecolor',
            field=models.CharField(default='black', max_length=40, verbose_name='Box title color'),
        ),
    ]
